[ctf_events]
enforceTypes = true
field.ctf_id = string
field.name = string
field.short_description = string
field.description = string
field.image_url = string
field.registration_opens = string
field.registration_closes = string
field.event_starts = string
field.event_ends = string
field.search_url = string
field.search_url_desc = string
field.scoring_url = string
field.participant_roles = string
field.enabled = string
field.allow_updates = string
field.allow_teams = string
field.created_at = string
field.updated_at = string

[ctf_registrations]
enforceTypes = true
field.ctf_id = string
field.Username = string
field.DisplayUsername = string
field.Team = string
field.FirstName = string
field.LastName = string
field.Email = string
field.SearchUrl = string
field.SearchUrlDesc = string
field.ScoringUrl = string
field.status = string
field.registered_at = string
field.updated_at = string
