[getanswer]
filename = getanswer.py
chunked = false
local = true
python.required = 3.9,3.13

[gethints]
filename = gethints.py
chunked = false
local = true
python.required = 3.9,3.13

[validateevents]
filename = validateevents.py
chunked = false
local = true
python.required = 3.9,3.13
