[getanswer]
filename = getanswer.py
chunked = false
local = true
python.required = 3.9,3.13
enableheader = true
passauth = true

[gethints]
filename = gethints.py
chunked = false
local = true
python.required = 3.9,3.13
enableheader = true
passauth = true

[validateevents]
filename = validateevents.py
chunked = false
local = true
python.required = 3.9,3.13
