[ctf_events]
external_type = kvstore
collection = ctf_events
fields_list = _key,ctf_id,name,short_description,description,image_url,registration_opens,registration_closes,event_starts,event_ends,search_url,search_url_desc,scoring_url,participant_roles,enabled,allow_updates,allow_teams,created_at,updated_at

[ctf_registrations]
external_type = kvstore
collection = ctf_registrations
fields_list = _key,ctf_id,Username,DisplayUsername,Team,FirstName,LastName,Email,SearchUrl,SearchUrlDesc,ScoringUrl,status,registered_at,updated_at